[package]
name = "tonik-activity"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
tokio = { version = "1.44.0", features = ["rt", "macros", "rt-multi-thread"] }
tonik = { path = "../tonik" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
