[package]
name = "tonik-sms"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
tokio = { version = "1.44.1", features = ["rt", "macros", "rt-multi-thread"] }
tonik = { path = "../tonik" }
